# Copyright (c) 2023 0x6flab
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at:
# http://www.apache.org/licenses/LICENSE-2.0

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "./.github/workflows"
    schedule:
      interval: "monthly"
      day: "sunday"
      time: "06:00"
      timezone: "Africa/Nairobi"
    assignees:
      - "rodneyosodo"
    reviewers:
      - "rodneyosodo"
