# Copyright (c) 2023 0x6flab
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at:
# http://www.apache.org/licenses/LICENSE-2.0

version: "2"

linters:
  default: all

  disable:
    - lll
    - wsl
    - depguard
    - gochecknoinits
    - exhaustruct
    - forbidigo
    - gosec
    - ireturn
    - paralleltest
    - thelper
    - varnamelen
    - wsl
    - copyloopvar # Disabled for go lower than 1.21
    - intrange # Disabled for go lower than 1.21

  settings:
    funlen:
      lines: -1
      statements: -1

    gocritic:
      enable-all: true
      disabled-checks:
        - emptyFallthrough
        - commentedOutCode

    goheader:
      values:
        const:
          COMPANY: 0x6flab
        regexp:
          YEAR: 20[0-9][0-9]
      template: |-
        Copyright (c) {{ YEAR }} {{ COMPANY }}

        Licensed under the Apache License, Version 2.0 (the "License");
        you may not use this file except in compliance with the License.
        You may obtain a copy of the License at:
        http://www.apache.org/licenses/LICENSE-2.0

  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - examples/main.go

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports

  exclusions:
    generated: lax
