# Copyright (c) 2023 0x6flab
#
# SPDX-License-Identifier: GNU GENERAL PUBLIC LICENSE

linters:
  enable-all: true
  fast: true
  disable:
    - misspell
    - lll
    - wsl
    - depguard
    - scopelint
    - nosnakecase
    - ifshort
    - gocognit
    - gochecknoinits

linters-settings:
  goheader:
    values:
      const:
        COMPANY: 0x6flab
      regexp: 
        YEAR: 20[0-9][0-9]
    template: |-
      Copyright (c) {{ YEAR }} {{ COMPANY }}

      SPDX-License-Identifier: GNU GENERAL PUBLIC LICENSE
  funlen:
    lines: -1
    statements: -1

  gomnd:
    ignored-files:
      - "examples/main.go"
