project_name: namegenerator

before:
  hooks:
    - go mod tidy

builds:
  - skip: true

archives:
  - format: tar.gz
    wrap_in_directory: true
    name_template: >-
      {{ .ProjectName }}_
      {{ .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md

checksum:
  name_template: "{{ .ProjectName }}-{{ .Version }}-checksums.txt"

snapshot:
  name_template: SNAPSHOT-{{ .Commit }}

source:
  enabled: true
  name_template: "{{ .ProjectName }}-{{ .Version }}-source"
