name: Test and coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '1.19'

      - name: Run coverage
        run: go test -mod=vendor -v --race -covermode=atomic -coverprofile cover.txt

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
